In [1]:
import numpy as np

In [2]:
#Create a NumPy array with values from 1 to 10.
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Create a 2D NumPy array with random values between 0 and 1.
array = np.random.rand(3,4)
array

array([[0.02131256, 0.55211406, 0.16750484, 0.78265968],
       [0.57439704, 0.8088056 , 0.55974005, 0.01877274],
       [0.77982082, 0.17824921, 0.51420456, 0.62570507]])

In [4]:
#Add 5 to all values in a NumPy array.
array=np.array([1,2,3,4,5])
array = array + 5
array

array([ 6,  7,  8,  9, 10])

In [5]:
#Multiply all values in a NumPy array by 2.
ar=np.array([10,20,30])
ar=ar * 2
ar

array([20, 40, 60])

In [6]:
from scipy import stats
ar1=np.array([1,2,3,4,4,4,4,5,6,4,7,7,8,8,9,10])
mean=np.mean(ar1)
median=np.median(ar1)
mode=stats.mode(ar1)
std=np.std(ar1)
print("Mean:",mean)
print("Median:",median)
print("Mode:",mode.mode[0])
print("Standard deviation:",std)

Mean: 5.375
Median: 4.5
Mode: 4
Standard deviation: 2.496873044429772


In [7]:
#Reshape a 1D NumPy array into a 2D array with 2 rows and 3 columns.
new_arr=np.array([2,4,6,8,10,12])
new_arr=new_arr.reshape(2,3)
new_arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
#Given a 2D NumPy array arr of shape (n, m), where n is the number of rows and m is the number of columns 
#write a Python function that returns a new 2D NumPy array where the values of each row are sorted in descending order.
arr = np.array([[3, 2, 4],
                [6, 5, 8],
                [9, 8, 10]])

def sort_rows(arr):
    # Sort each row of the array in descending order
    sorted_arr = np.sort(arr, axis=1)[:,::-1]
    return sorted_arr
sort_rows(arr)

array([[ 4,  3,  2],
       [ 8,  6,  5],
       [10,  9,  8]])

In [9]:
arr = np.array([[4, 2, 3],
                [8, 9, 7],
                [1, 6, 5]])
sorted_arr = np.sort(arr, axis=1)[:,::-1]

In [10]:
sorted_arr

array([[4, 3, 2],
       [9, 8, 7],
       [6, 5, 1]])

In [11]:
np.__version__

'1.21.5'

In [12]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
   

# Write a NumPy program to test whether none of the elements of a given array are zero.

In [13]:
# create a sample array
arr = np.array([1, 2, 3, 4, 5])

# check if any of the elements are zero
result = np.all(arr != 0)

# print the result
print(result)

True


In [14]:
arr = np.array([0, 0, 0, 1, 0])

# check if any of the elements are non-zero
result = np.any(arr != 0)

# print the result
print(result)

True


In [15]:
np.sort(arr)

array([0, 0, 0, 0, 1])

In [16]:
# create a sample array with some finite and non-finite values
arr = np.array([1, 2, np.inf, np.nan, 5])

# test the array element-wise for finiteness
result = np.isfinite(arr)

# print the result
print(result)

[ True  True False False  True]


In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2,10,dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [22]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [23]:
np.diag([1,2,3],1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [24]:
a=np.array([[1,2],[3,4]])
np.diag(a)

array([1, 4])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [27]:
np.vander(np.linspace(0,2,5),2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [28]:
np.vander(np.linspace(0,3,7),3)

array([[0.  , 0.  , 1.  ],
       [0.25, 0.5 , 1.  ],
       [1.  , 1.  , 1.  ],
       [2.25, 1.5 , 1.  ],
       [4.  , 2.  , 1.  ],
       [6.25, 2.5 , 1.  ],
       [9.  , 3.  , 1.  ]])

In [29]:
np.vander([1,2,3,4],2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [30]:
np.vander([1,2,3,4],4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [31]:
np.vander([1,2,3,4],3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [32]:
np.vander([10,20,30,40],4)

array([[ 1000,   100,    10,     1],
       [ 8000,   400,    20,     1],
       [27000,   900,    30,     1],
       [64000,  1600,    40,     1]])

In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
from numpy.random import default_rng
default_rng().random((2,3))

array([[0.07347188, 0.5482572 , 0.82083942],
       [0.70675848, 0.56977331, 0.67142181]])

In [37]:
from numpy.random import default_rng
default_rng(20).random((3,5))

array([[0.28007596, 0.46114671, 0.12171969, 0.52260835, 0.40916841],
       [0.07163955, 0.09896668, 0.98628836, 0.69406788, 0.44868846],
       [0.64017681, 0.27048886, 0.30187397, 0.07334207, 0.05258557]])

In [38]:
a=np.array([1,2,3,4,5])
b=a[:2]
b=b+1
print(a)
print(b)

[1 2 3 4 5]
[2 3]


In [39]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


In [40]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))

In [41]:
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [42]:
x=np.arange(10)

In [43]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x[2]

2

In [45]:
x[0]

0

In [46]:
x[1]

1

In [47]:
x[-1]

9

In [48]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

In [52]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])