In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
print(np.__version__)

1.21.5


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr = np.array(96)
print(arr)

96


In [5]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
import numpy as np
arr = np.array([[[10,20,30], [40, 50, 60]], [[10, 20, 30], [40, 50, 60]]])
print(arr)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]


In [8]:
import numpy as np
a = np.array(71)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print('First element of the array:',arr[0])

First element of the array: 1


In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print('Second element of the array:',arr[1])

Second element of the array: 2


In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [13]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [14]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [15]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [16]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [23]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [24]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [25]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [26]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [27]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [28]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [29]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [30]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [31]:
import numpy as np
arr = np.array([1, 2, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [32]:
import numpy as np
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [33]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [34]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [35]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [36]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [37]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [38]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [40]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [41]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [43]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
for x in arr:
    print(x)

1
2
3
4
5


In [44]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [45]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [46]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [47]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [48]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [49]:
import numpy as np
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [50]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [51]:
import numpy as np
arr = np.array([1, 2, 3])
for d, x in np.ndenumerate(arr):
    print(d, x)

(0,) 1
(1,) 2
(2,) 3


In [52]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for m, x in np.ndenumerate(arr):
    print(m, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [53]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [54]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [55]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [56]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [57]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [58]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [59]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [60]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [61]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [62]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [63]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [64]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [65]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [66]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [67]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [68]:
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [69]:
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [70]:
import numpy as np
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [71]:
import numpy as np
arr = np.array(['banana', 'cherry', 'apple','strabery','kiwi'])
print(np.sort(arr))

['apple' 'banana' 'cherry' 'kiwi' 'strabery']


In [72]:
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [73]:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [74]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [75]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [76]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [77]:
from numpy import random
x = random.randint(100)
print(x)

20


In [78]:
from numpy import random
x = random.rand()
print(x)

0.5390413961104233


In [79]:
from numpy import random
x=random.randint(100, size=(5))
print(x)

[69 20 43 45 19]


In [80]:
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)

[[57 11 19 74 91]
 [79 58 97 19 29]
 [ 0 48 33 45 19]]


In [81]:
from numpy import random
x = random.rand(5)
print(x)

[0.46278719 0.7124923  0.86866589 0.69298632 0.48539   ]


In [82]:
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.16408087 0.09806347 0.04178936 0.6904769  0.66342159]
 [0.1300165  0.26892219 0.35624835 0.04078382 0.42910888]
 [0.69210833 0.05968936 0.7223849  0.3001305  0.78971564]]


In [83]:
from numpy import random
x = random.choice([3, 5, 7, 9,17,44,81,90])
print(x)

5


In [84]:
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[9 5 3 9 5]
 [5 7 9 9 7]
 [7 7 3 5 5]]


In [85]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[5 7 5 5 7 5 7 5 7 7 5 3 5 5 5 3 5 7 7 7 5 7 7 5 5 7 5 3 5 7 7 5 3 7 5 5 5
 3 5 5 7 3 7 7 7 7 7 5 3 3 7 7 7 7 7 7 7 7 7 5 7 7 7 5 3 7 3 7 7 7 7 7 3 7
 3 5 7 5 7 7 7 5 7 5 5 5 7 7 7 7 5 5 5 5 7 5 7 7 5 7]


In [86]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[5 7 7 7 7]
 [7 7 7 5 7]
 [7 7 7 5 5]]


In [87]:
from numpy import random
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[1 4 5 2 3]


In [88]:
import numpy as np
#lst=[1,2,3,4,5,6,7,8,9,10]
#np.array(lst)
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
arr.shape
print('The index:',arr[3])

[1 2 3 4 5]
<class 'numpy.ndarray'>
The index: 4


In [89]:
lst1=[1,2,3,4,5]
lst2=[2,4,6,8,10]
lst3=[7,9,11,13,15]
arr1=np.array([lst1,lst2,lst3])
print('The 2D array looks like:\n',arr1)
print('The shape of the array is:',arr1.shape)
#arr1[:]
#arr1[1:]
arr1[::-1]
arr1[::-2]
arr1[:,4:]
arr1[1:,3:]
arr1[:,3:].shape
arr1[:,-5::4]

The 2D array looks like:
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 7  9 11 13 15]]
The shape of the array is: (3, 5)


array([[ 1,  5],
       [ 2, 10],
       [ 7, 15]])

In [90]:
arr1[arr1>2]

array([ 3,  4,  5,  4,  6,  8, 10,  7,  9, 11, 13, 15])

In [91]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  6,  8],
       [10,  7,  9],
       [11, 13, 15]])

In [92]:
arr1[:,-3::2]

array([[ 3,  5],
       [ 6, 10],
       [11, 15]])

In [93]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [94]:
np.arange(1,20,2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [95]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [97]:
np.arange(1,20,2).reshape(1,10,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [98]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [99]:
arr1*arr1

array([[  1,   4,   9,  16,  25],
       [  4,  16,  36,  64, 100],
       [ 49,  81, 121, 169, 225]])

In [100]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [ 4,  8, 12, 16, 20],
       [14, 18, 22, 26, 30]])

In [101]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [102]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [103]:
np.random.randint(10,30,4).reshape(2,2)

array([[10, 22],
       [23, 26]])

In [104]:
np.random.randn(3,4)

array([[-0.6260448 , -0.03978338, -0.22712702, -0.32350434],
       [-0.71410596,  0.57762334,  0.4077999 ,  0.24458092],
       [-1.0485035 ,  1.2427869 ,  0.31057861,  1.5200984 ]])

In [105]:
np.random.random_sample()

0.24676652995311477