# Write a program to convert a string element to uppercase, lowercase, capitalise the first letter, title-case and swapcase of a given NumPy array.

In [1]:
import numpy as np

In [2]:
arr=np.array(['I','am','Learning','PYTHON','NumPy','Library'],dtype=str)
upper_case=np.char.upper(arr)
lower_case=np.char.lower(arr)
capital_case=np.char.capitalize(arr)
swap_case=np.char.swapcase(arr)
title_case=np.char.title(arr)
print(upper_case)
print(lower_case)
print(capital_case)
print(swap_case)
print(title_case)

['I' 'AM' 'LEARNING' 'PYTHON' 'NUMPY' 'LIBRARY']
['i' 'am' 'learning' 'python' 'numpy' 'library']
['I' 'Am' 'Learning' 'Python' 'Numpy' 'Library']
['i' 'AM' 'lEARNING' 'python' 'nUMpY' 'lIBRARY']
['I' 'Am' 'Learning' 'Python' 'Numpy' 'Library']


# Write a program to transform elements of a given string to a numeric string of 10 digits by making all the elements of a given string to a numeric string of 8 digits with zeros on the left.

In [3]:
arr1=np.array(['23','7','1234','411','91432'],dtype=str)
zero_fill=np.char.zfill(arr1,8)
print(zero_fill)

['00000023' '00000007' '00001234' '00000411' '00091432']


# Write a program for inserting space between characters of all elements in a NumPy array.

In [4]:
arr2=np.array(['I','Learn','Python','And',"NumPy"])
insert_space=np.char.join(" ",arr2)
print(insert_space)

['I' 'L e a r n' 'P y t h o n' 'A n d' 'N u m P y']


# Write a program to repeat each of the elements five times for a given array.

In [5]:
arr3=np.array(['Numpy','Library','is','Easy'],dtype=str)
repeat=np.char.multiply(arr3,5)
print(repeat)

['NumpyNumpyNumpyNumpyNumpy' 'LibraryLibraryLibraryLibraryLibrary'
 'isisisisis' 'EasyEasyEasyEasyEasy']


# Write a program for creating an integer array with values belonging to the range 10 and 60

In [6]:
arr4=np.arange(10,60)
print(arr4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]


# Write a program to add a border of zeros around the existing array.

In [7]:
import numpy as np
one_arr=np.ones((4,4))

z_round=np.pad(one_arr,pad_width=1,mode='constant', constant_values=0)
  
print(z_round)           

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Write a program for changing the dimension of a NumPy array.

In [8]:
arr5=np.array([1,2,3,4,5,6,7,8,9])
print("original shape",arr5.shape)
print("-"*15)
arr5.shape=(3,3)
print("Transformed matrix \n",arr5)
print("Change dimension",arr5.shape)

original shape (9,)
---------------
Transformed matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Change dimension (3, 3)


# Write a program for interchanging two axes of the NumPy array.

In [9]:
arr6=np.array([[1,2,3]])
print("Original array",arr6)
axis_swap=np.swapaxes(arr6,0,1)
print("After swapping\n",axis_swap)

Original array [[1 2 3]]
After swapping
 [[1]
 [2]
 [3]]
