In [1]:
year=eval((input("Enter the year:")))
if (year%4)==0 and (year%100)==0 and (year%400)==0:
    print("{0} is leap year".format(year))
else:
    print("{0} is not a leap year".format(year))

Enter the year:2023
2023 is not a leap year


In [2]:
a=input("Enter the string:")
rev=""
for ch in a:
    rev=ch+rev
print(rev)
if a==rev:
    print("String is palindrome")
else:
    print("String is not a palindrome ")

Enter the string:NITIN
NITIN
String is palindrome


In [3]:
num=int(input("Enter the number:"))
rev=0
while (num>0):
    dg=num%10
    rev=rev*10+dg
    num=num//10
print("The reverse of number is",rev)

Enter the number:7007
The reverse of number is 7007


In [4]:
def fac(a):
    fac=1
    for p in range(a,0,-1):
        fac=fac*p
    return fac
n=int(input('Enter a number:'))
res=fac(n)
print("factorial of ",n,"is",res)

Enter a number:5
factorial of  5 is 120


In [5]:
for x in range(7):
    if (x==3 or x==6):
        continue
    print(x)

0
1
2
4
5


In [6]:
lsa={'class':12,'division':'A','rno':41}
print(lsa['class'])
print(lsa['division'])
print(lsa['rno'])
type(lsa)

12
A
41


dict

In [7]:
class india():
    def capital(self):
        print("New delhi is the capital of india")
    def language(self):
        print("Hindi is the language")
    def type(self):
        print("India is developing country")
class USA():
    def capital(self):
        print("Washington D.C is the capital ")
    def language(self):
        print("English is the language")
    def type(self):
        print("USA is a developed country")
obj_ind=india()
obj_usa=USA()
for country in(obj_ind,obj_usa):
    country.capital()
    country.language()
    country.type()

New delhi is the capital of india
Hindi is the language
India is developing country
Washington D.C is the capital 
English is the language
USA is a developed country


In [8]:
s="python is object oriented language"
s1=[]
for i in s.split():
    s1.append(len(i))
print(max(s1));print(min(s1))

8
2


In [9]:
s="python is easy"
s1=s.title()
result=""
for i in s1.split():
    result=result + i[:-1]+i[-1].upper()
    print(result)

PythoN
PythoNIS
PythoNISEasY


In [10]:
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [14]:
np.info(np.dtype)

 dtype()

dtype(dtype, align=False, copy=False)

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
dtype
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.

See also
--------
result_type

Examples
--------
Using array-scalar type:

>>> np.dtype(np.int16)
dtype('int16')

Structured type, one field name 'f1', containing int16:

>>> np.dtype([('f1', np.int16)])
dtype([('f1', 

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [18]:
np.arange(2,21)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [19]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [20]:
np.arange(11,0,-1)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [21]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np.arange(1,12)[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [23]:
np.__version__

'1.21.5'

In [24]:
!pip install pandas

In [25]:
!pip install numpy

In [26]:
import pandas as pd
pd.__version__

'1.4.2'

In [27]:
np.linspace(2,20)

array([ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
        3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
        5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
        7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
        9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653,
       11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
       13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
       14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
       16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
       18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ])

In [28]:
np.random.randint(50)

14

In [29]:
np.linspace(2,6,num=10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [30]:
np.linspace(-6,6,8)

array([-6.        , -4.28571429, -2.57142857, -0.85714286,  0.85714286,
        2.57142857,  4.28571429,  6.        ])

In [31]:
np.linspace(-6,6,13)

array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])

In [32]:
np.linspace(2,6,num=10,retstep=True)

(array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
        4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]),
 0.4444444444444444)

In [33]:
np.full((4,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [34]:
np.full((3,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [35]:
np.random.rand(5)

array([0.05131604, 0.75170686, 0.29189394, 0.31228433, 0.51019543])

In [36]:
np.random.rand(5,5)

array([[0.28697703, 0.06457046, 0.5669115 , 0.81927377, 0.18242471],
       [0.31436931, 0.82423966, 0.67181788, 0.89458219, 0.72290038],
       [0.62755999, 0.84923747, 0.878655  , 0.81538028, 0.49333867],
       [0.46042805, 0.32698502, 0.83440182, 0.0812815 , 0.70613954],
       [0.98872614, 0.99665478, 0.94279391, 0.28264148, 0.31682242]])

In [37]:
d=np.random.rand(5)
print(d.dtype)
print(d.size)
print(d.shape)

float64
5
(5,)


In [38]:
d.ndim

1

In [39]:
d.ndim

1