In [1]:
user_input=input("Enter any two values")
split_user_input=user_input.split()
a=split_user_input[0]
b=split_user_input[1]
print(a);print(b)

Enter any two values97 72
97
72


In [2]:
import numpy as np
import pandas as pd

In [3]:
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])
print(a);print(b)

[10 20 30 40 50]
[1 2 3 4 5]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
def dp(a,b):
    for i in range(5):
        print(a[i],b[i])
dp(a,b)

10 1
20 2
30 3
40 4
50 5


In [6]:
print(a.ndim);print(b.ndim)

1
1


In [7]:
print(a[1:3])

[20 30]


In [8]:
print(a[:])

[10 20 30 40 50]


In [9]:
print(b[:])

[1 2 3 4 5]


In [10]:
print(a[:-1])

[10 20 30 40]


In [11]:
print(a[::-1])

[50 40 30 20 10]


In [12]:
print(b[::-1])

[5 4 3 2 1]


In [13]:
print(a[1::-1])

[20 10]


In [14]:
print(b[1::-1])

[2 1]


In [15]:
print(a[1])

20


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=(arr.reshape(2,4).base)
print(newarr)

[1 2 3 4 5 6 7 8]


In [19]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [20]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [21]:
import numpy as np
arr=np.array([1,2,3,4])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [22]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [23]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [24]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [25]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [26]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.hsplit(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [27]:
d=np.array([20,45,98,43,7,8,12,71,65])
print(np.sort(d))

[ 7  8 12 20 43 45 65 71 98]


In [28]:
sor=np.array(['cherry','bannana','mango','kivi'])
print(np.sort(sor))

['bannana' 'cherry' 'kivi' 'mango']


In [29]:
bl=np.array([True,False,True,False,True,True])
print(np.sort(bl))

[False False  True  True  True  True]


In [30]:
arr=np.array([91,92,93,94,95])
x=[True,False,True,False,True]
newarr=arr[x]
print(newarr)

[91 93 95]


In [31]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr=arr%2==0
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [33]:
a,b=input("Enter the values:").split(",")
print(a)
print(b)

Enter the values:102,103
102
103


In [35]:
x,y,z=input("Enter the values").split()
print(x)
print(y)
print(z)

Enter the values32 43 21
32
43
21


In [36]:
txt = " hi my name is sunil"
a =txt.split()
print(a)

['hi', 'my', 'name', 'is', 'sunil']


In [37]:
txt =("tea, coffee, milk") 
a =txt.split(",")
print(a)

['tea', ' coffee', ' milk']


In [38]:
txt="#orange#strawberry#grapes#banana"
a=txt.split("#")
print(a)

['', 'orange', 'strawberry', 'grapes', 'banana']


In [39]:
x = int(input("Enter x: "))
y = int(input("Enter y: "))
added = x+y
print("The sum of {0} and {1} is {2}".format(x,y,added))

Enter x: 190
Enter y: 110
The sum of 190 and 110 is 300


In [40]:
x,y = map(int,input("Enter Two Numbers separated by space.\n").split(" "))
added = x+y
print("The sum of {0} and {1} is {2}".format(x,y,added))

Enter Two Numbers separated by space.
34 67
The sum of 34 and 67 is 101


In [41]:
st=input("enter the age")
print("my age is {}".format(st))

enter the age34
my age is 34


In [42]:
users=['Sunil','Anil','Sachin','Dipak','Santosh']
computer=['Computer1','Iphone','Podcast','Mic Pc','Desktop']
for i in range(0,len(users)):
    print("User Name:",users[i],"used by",computer[i])

User Name: Sunil used by Computer1
User Name: Anil used by Iphone
User Name: Sachin used by Podcast
User Name: Dipak used by Mic Pc
User Name: Santosh used by Desktop


In [43]:
for i in range(0,len(users)):
    temp="User name {0} is used by {1}"
    print(temp.format(users[i],computer[i]))

User name Sunil is used by Computer1
User name Anil is used by Iphone
User name Sachin is used by Podcast
User name Dipak is used by Mic Pc
User name Santosh is used by Desktop


In [44]:
print(int(input("Enter x: "))+int(input("Enter y: ")))

Enter x: 102
Enter y: 103
205


In [45]:
x=list(map(int,input("Enter multiple values:").split()))
print("List of students: ",x)

Enter multiple values:12 13 14 15 16 17
List of students:  [12, 13, 14, 15, 16, 17]


In [46]:
l=[1,2,3,4,5,6,7,8,9,10]
print(*l)

1 2 3 4 5 6 7 8 9 10


In [48]:
x,y=[x for x in input("Enter the 2 values :").split()]
print("First no. is {} and second no. is {}".format(x,y))

Enter the 2 values :3005 1000
First no. is 3005 and second no. is 1000
